PlacowkaOswiatowaQuiz/Controllers/DiagnosisController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using PlacowkaOswiatowaQuiz.Helpers;
using PlacowkaOswiatowaQuiz.Interfaces;
using PlacowkaOswiatowaQuiz.Shared.DTOs;
using PlacowkaOswiatowaQuiz.Shared.ViewModels;

namespace PlacowkaOswiatowaQuiz.Controllers
{
    public class DiagnosisController : Controller
    {
        #region Prywatne pola
        private readonly IHttpClientService _httpClient;
        #endregion

        #region Konstruktor
        public DiagnosisController(
            IHttpClientService httpClient)
        {
            _httpClient = httpClient;
        }
        #endregion

        #region Lista wszystkich utworzonych formularzy
        public async Task<IActionResult> Index()
        {
            var diagnosis = new List<DiagnosisViewModel>();
            try
            {
                diagnosis = await _httpClient.GetAllItems<DiagnosisViewModel>();
                return View(diagnosis);
            }
            catch (HttpRequestException e)
            {
                TempData["errorAlert"] = $"Nie udało się pobrać wszystkich" +
                    $"formularzy diagnoz. \nOdpowiedź serwera: '{e.Message}'";
                return View(diagnosis);
            }
        }
        #endregion

        #region Zapis wyniku wybranej oceny zestawu pytań
        //Przerobione na endpoint do obsługi jQuery AJAX
        [HttpPost]
        public async Task<IActionResult> SaveResult(ResultViewModel resultVM)
        {
            if (!ModelState.IsValid)
                return BadRequest("Błąd formularza");

            try
            {
                var createResultDto = new CreateResultDto
                {
                    Id = resultVM.Id,
                    DiagnosisId = resultVM.DiagnosisId,
                    RatingId = resultVM.QuestionsSetRating.Id,
                    RatingLevel = resultVM.RatingLevel.Value,
                    Notes = resultVM.Notes
                };

                await _httpClient.AddItem(createResultDto);

                return Ok("Poprawnie zapisano rezultat");
            }
            catch (Exception e)
            {
                return BadRequest($"Nie udało się zapisać oceny" +
                    $"\nOdpowiedź serwera: '{e.Message}'");
            }
        }
        #endregion

        #region Wyświetlanie formularza diagnozy (tworzenie/edycja)
        public async Task<IActionResult> Form([FromQuery] int diagnosisId)
        {
            var diagnosis = new DiagnosisViewModel();
            try
            {
                diagnosis = await _httpClient.GetItemById<DiagnosisViewModel>(diagnosisId);

                if (diagnosis.ReportId.HasValue)
                    throw new DataValidationException(
                        "Nie można edytować diagnozy, która posiada wygenerowany raport");

                //jeżeli jest to edycja, to listę identyfikatorów zestawów pytań można
                //wyciągnąć z wyników diagnozy
                if (diagnosis.Results?.Count > 0)
                {
                    diagnosis.IsForEdit = true;
                    diagnosis.QuestionsSetsIds = diagnosis.Results
                        .Select(r => r.QuestionsSetRating.QuestionsSetId).ToList();
                }
                else
                {
                    var questionsSets = await _httpClient.GetAllItems<QuestionsSetViewModel>(
                        ("difficultyId", diagnosis.Difficulty.Id));

                    //Lista identyfikatorów zestawów pytań, których modele będą pobrane 
                    //asynchronicznie na etapie przełączania zestawów na formularzu diagnozy
                    diagnosis.QuestionsSetsIds = questionsSets.Select(qs => qs.Id).ToList();
                }

                //if(ids?.Count < 1) - nie zwaliduje dla listy = null
                if (!(diagnosis.QuestionsSetsIds?.Count > 0))
                    throw new ArgumentNullException(nameof(diagnosis.QuestionsSetsIds));

                return View(diagnosis);
            }
            catch (HttpRequestException e)
            {
                TempData["errorAlert"] = $"Nie udało się pobrać formularza diagnozy" +
                    $"\nOdpowiedź serwera: '{e.Message}'";
                return RedirectToAction(nameof(Index));
            }
            catch(Exception e)
            {
                TempData["errorAlert"] = e.Message;
                return RedirectToAction(nameof(Index));
            }
        }

        //pobranie części dot. zestawu pytań
        public async Task<IActionResult> QuestionsSetPartial([FromQuery] int questionsSetId)
        {
            try
            {
                var questionsSet =
                    await _httpClient.GetItemById<QuestionsSetViewModel>(questionsSetId);
                return PartialView("_QuestionsSet", questionsSet);
            }
            catch (Exception e)
            {
                TempData["errorAlert"] = $"Nie udało się pobrać zestawu pytań." +
                    $"\nOdpowiedź serwera: '{e.Message}'";
                return PartialView("_QuestionsSet", new QuestionsSetViewModel());
            }
        }

        //pobranie części dot. oceny zestawu pytań
        public async Task<IActionResult> ResultPartial([FromQuery] int diagnosisId,
            [FromQuery] int questionsSetId)
        {
            var result = new ResultViewModel() { DiagnosisId = diagnosisId };
            try
            {
                result = await _httpClient.GetItemById<ResultViewModel>(null,
                    (nameof(diagnosisId), diagnosisId),
                    (nameof(questionsSetId), questionsSetId));
                    
                return PartialView("_Result", result);
            }
            catch(Exception e)
            {
                //Tutaj jeżeli nie znaleziono, (api zwraca NotFound),
                //to poprostu wynik nie jest uzupełniany
                //trzeba osobno obsłużyć problem z połączeniem do api
                return PartialView("_Result", result);
            }
        }
        #endregion

        #region Tworzenie formularza diagnozy
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(CreateDiagnosisViewModel diagnosisVM)
        {
            if (!ModelState.IsValid)
                return View(diagnosisVM);
            try
            {
                //DifficultyId jest wymagane na formularzu
                var availableQuestionsSets = await _httpClient.GetAllItems<QuestionsSetViewModel>(
                    ("difficultyId", diagnosisVM.DifficultyId.Value)) ??
                    new List<QuestionsSetViewModel>();

                if (!availableQuestionsSets.Any())
                    throw new DataValidationException(
                        "Brak dostępnych zestawów pytań dla wybranej skali trudności. " +
                        "Proszę dodać zestawy pytań i ponownie utworzyć formularz diagnozy.");

                var emptyQuestionsSetsIds = availableQuestionsSets
                    .Where(qs => !qs.Questions.Any())
                    .Select(qs => qs.Id)
                    .ToList();

                if (emptyQuestionsSetsIds.Any())
                    throw new DataValidationException(
                        "Jeden z zestawów pytań dostępnych dla diagnozy, " +
                        "nie posiada pytań składowych. Proszę uzupełnić pytania " +
                        "i ponownie utworzyć formularz diagnozy. " +
                        "Lista identyfikatorów pustych zestawów pytań: " +
                        $"{string.Join(", ", emptyQuestionsSetsIds)}");

                var createDiagnosisDto = (CreateDiagnosisDto)diagnosisVM;
                var createdDiagnosisId = await _httpClient.AddItem(createDiagnosisDto);
                //Po utworzeniu diagnozy, przekierowanie do formularza (pierwszego zestawu pytań)
                return RedirectToAction(nameof(Form), new { diagnosisId = createdDiagnosisId });
            }
            catch(DataValidationException e)
            {
                TempData["errorAlert"] = $"Nie udało się utworzyć formularza diagnozy. {e.Message}";
                return View(diagnosisVM);
            }
            catch (Exception e)
            {
                TempData["errorAlert"] = $"Nie udało się utworzyć formularza diagnozy." +
                    $"\nOdpowiedź serwera: '{e.Message}'";
                return View(diagnosisVM);
            }
        }
        #endregion

        #region Podsumowanie/szczegóły formularza diagnozy
        //Przekazywanie parametru przez Route wymaga ręcznego zadeklarowania endpointu
        [HttpGet("Diagnosis/Details/{diagnosisId}")]
        public async Task<IActionResult> Details([FromRoute] int diagnosisId)
        {
            var diagnosisSummary = new DiagnosisSummaryViewModel();
            try
            {
                diagnosisSummary = await GetDiagnosisSummary(diagnosisId);
                return View(diagnosisSummary);
            }
            catch(HttpRequestException e)
            {
                TempData["errorAlert"] = "Nie udało się pobrać formularza diagnozy o " +
                    $"podanym identyfikatorze {diagnosisId}. Odpowiedź serwera: '{e.Message}'";
                return RedirectToAction(nameof(Index));
            }
        }
        #endregion

        #region Metody prywatne
        private async Task<DiagnosisSummaryViewModel> GetDiagnosisSummary(int diagnosisId)
        {
            var diagnosis = await _httpClient.GetItemById<DiagnosisViewModel>(diagnosisId);

            var askedQuestionSetsIds = new List<int>();
            //QuestionsSetRating (ocena zestawu pytań) jest wymagana do podania,
            //więc na pewno istnieje, jeżeli istnieje powiązany z diagnozą Result (wynik)
            if (diagnosis.Results?.Count > 0)

PlacowkaOswiatowaQuiz/Controllers/EmployeeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.WebUtilities;
using Microsoft.Extensions.Options;
using PlacowkaOswiatowaQuiz.Helpers.Options;
using PlacowkaOswiatowaQuiz.Interfaces;
using PlacowkaOswiatowaQuiz.Shared.ViewModels;

namespace PlacowkaOswiatowaQuiz.Models.Controllers
{
    public class EmployeeController : Controller
    {
        #region Pola prywatne
        private readonly IHttpClientService _httpClient;
        #endregion

        #region Konstruktor
        public EmployeeController(IHttpClientService httpClient)
        {
            _httpClient = httpClient;
        }
        #endregion

        #region Pobieranie wszystkich pracowników
        public async Task<IActionResult> Index()
        {
            var employees = new List<EmployeeViewModel>();
            try
            {
                employees = await _httpClient.GetAllItems<EmployeeViewModel>();
                return View(employees);
            }
            catch(Exception e)
            {
                TempData["errorAlert"] =
                    $"Nie udało się pobrać wszystkich pracowników. '{e.Message}'";
                return View(employees);
            }
        }

        //Do pobierania asynchronicznego
        public async Task<IActionResult> GetAllEmployees()
        {
            try
            {
                var employees = await _httpClient.GetAllItems<EmployeeViewModel>();
                return Ok(employees);
            }
            catch(Exception e)
            {
                return BadRequest(e.Message);
            }

        }
        #endregion
    }
}

PlacowkaOswiatowaQuiz/Controllers/QuestionController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using Microsoft.AspNetCore.WebUtilities;
using Newtonsoft.Json;
using PlacowkaOswiatowaQuiz.Helpers;
using PlacowkaOswiatowaQuiz.Helpers.Options;
using PlacowkaOswiatowaQuiz.Interfaces;
using PlacowkaOswiatowaQuiz.Shared.ViewModels;

namespace PlacowkaOswiatowaQuiz.Controllers
{
    public class QuestionController : Controller
    {
        #region Pola prywatne
        private readonly IHttpClientService _httpClient;
        #endregion

        #region Konstruktor
        public QuestionController(IHttpClientService httpClient)
        {
            _httpClient = httpClient;
        }
        #endregion

        #region Wszystkie pytania
        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var questions = new List<QuestionViewModel>();
            try
            {
                questions = await _httpClient.GetAllItems<QuestionViewModel>();
                return View(questions);
            }
            catch(Exception e)
            {
                TempData["errorAlert"] = $"Nie udało się pobrać wszystkich pytań. " +
                    $"'{e.Message}'";
                return View(questions);
            }
        }
        #endregion

        #region Edycja/Tworzenie pytania
        [HttpGet]
        public async Task<IActionResult> Edit(int id, int questionsSetId)
        {
            var question = new QuestionViewModel
            {
                QuestionsSetId = questionsSetId,
                IsFromQuestionsSet = questionsSetId != 0
            };

            if (id == default(int))
                return View(question);

            try
            {
                question = await _httpClient.GetItemById<QuestionViewModel>(id);
                question.IsFromQuestionsSet = questionsSetId != 0;

                return View(question);
            }
            catch(Exception e)
            {
                TempData["errorAlert"] = e.Message;
                return View(question);
            }
        }

        [HttpPost]
        public async Task<IActionResult> Edit(QuestionViewModel questionVM)
        {
            if (!ModelState.IsValid)
                return View(questionVM);

            try
            {
                if (questionVM.Id == default(int))
                    await _httpClient.AddItem(questionVM);
                else
                    await _httpClient.UpdateItem(questionVM);

                TempData["successAlert"] = "Poprawnie zaktualizowano/dodano pytanie";

                if (questionVM.IsFromQuestionsSet)
                    return RedirectToAction("Details", "QuestionsSet",
                        new { id = questionVM.QuestionsSetId });

                return RedirectToAction(nameof(Index));
            }
            catch(Exception e)
            {
                TempData["errorAlert"] = "Nieudana próba edycji/utworzenia pytania. " +
                    $"'{e.Message}'";
                return View(questionVM);
            }
        }
        #endregion

        #region Usuwania pytania
        //Do zapytań asynchronicznych
        [HttpDelete]
        public async Task<IActionResult> Delete(int id)
        {
            if (id == default)
                return BadRequest("Nie znaleziono rekordu o podanym identyfikatorze");
            try
            {
                await _httpClient.DeleteItemById<QuestionViewModel>(id);
                return NoContent();
            }
            catch (Exception e)
            {
                return BadRequest(e.Message);
            }
        }
        #endregion
    }
}

PlacowkaOswiatowaQuiz/Controllers/StudentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using PlacowkaOswiatowaQuiz.Helpers.Filters;
using PlacowkaOswiatowaQuiz.Helpers.Options;
using PlacowkaOswiatowaQuiz.Interfaces;
using PlacowkaOswiatowaQuiz.Shared.ViewModels;

namespace PlacowkaOswiatowaQuiz.Controllers
{
    public class StudentController : Controller
    {
        #region Pola prywatne
        private readonly IHttpClientService _httpClient;
        #endregion

        #region Konstruktor
        public StudentController(IHttpClientService httpClient)
        {
            _httpClient = httpClient;
        }
        #endregion

        #region Pobranie wszystkich uczniów
        public async Task<IActionResult> Index()
        {
            var students = new List<StudentViewModel>();
            try
            {
                students = await _httpClient.GetAllItems<StudentViewModel>();
                return View(students);
            }
            catch(Exception e)
            {
                TempData["errorAlert"] =
                    $"'Nie udało się pobrać wszystkich uczniów. {e.Message}'";
                return View(students);
            }
        }

        //Do pobieranie asynchronicznego
        public async Task<IActionResult> GetAllStudents()
        {
            try
            {
                var students = await _httpClient.GetAllItems<StudentViewModel>();
                return Ok(students);
            }
            catch(Exception e)
            {
                return BadRequest(e.Message);
            }
        }
        #endregion
    }
}

PlacowkaOswiatowaQuiz/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/PlacowkaOswiatowaQuiz.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/toastr.css" asp-append-version="true" />
    <script src="~/lib/jquery/dist/jquery.min.js"></script>

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light border-bottom box-shadow mb-3"
             style="background-color: #DEDEDE; ">
            <div class="container-fluid">
                <a class="navbar-brand" asp-controller="Home" asp-action="Index">
                    <img src="@Url.Content("~/images/school_v2.svg")"
                         width="40" height="30" class="d-inline-block align-text-top">
                    Placówka Oświatowa
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                        data-bs-target=".navbar-collapse"
                        aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Employee" asp-action="Index">
                                Pracownicy
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Student" asp-action="Index">
                                Uczniowie
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="QuestionsSet" asp-action="Index">
                                Zestawy pytań
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Question" asp-action="Index">
                                Pytania
                            </a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button"
                               aria-haspopup="true"
                               aria-expanded="false">
                                Dane słownikowe
                            </a>
                            <div class="dropdown-menu">
                                <a class="dropdown-item" asp-controller="Dictionary" asp-action="IndexArea">
                                    Obszary
                                </a>
                                <a class="dropdown-item" asp-controller="Dictionary" asp-action="IndexDifficulty">
                                    Skale trudności
                                </a>
                            </div>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Diagnosis" asp-action="Index">
                                Diagnozy
                            </a>
                        </li>
                    </ul>
                    @await Html.PartialAsync("_LoginPartial", new LoginViewModel())
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="d-flex align-items-end flex-column container">
            &copy; @DateTime.Now.Year - Placówka Oświatowa - Diagnoza,
            autor: Filip Rzeźniczak
        </div>
    </footer>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/lib/sweetalert/sweetalert.min.js"></script>
    <script src="~/lib/sweetalert/sweetalert2.js"></script>
    <script src="~/js/toastr.js"></script>
    @await Html.PartialAsync("_ValidationScriptsPartial")

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>