PlacowkaOswiatowaQuiz/Controllers/DictionaryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using PlacowkaOswiatowaQuiz.Helpers;
using PlacowkaOswiatowaQuiz.Helpers.Options;
using PlacowkaOswiatowaQuiz.Interfaces;
using PlacowkaOswiatowaQuiz.Shared.ViewModels;

namespace PlacowkaOswiatowaQuiz.Controllers
{
    public class DictionaryController : Controller
    {
        #region Pola prywatne
        private readonly IHttpClientService _httpClient;
        #endregion

        #region Konstruktor
        public DictionaryController(IHttpClientService httpClient)
        {
            _httpClient = httpClient;
        }
        #endregion

        #region Obszar zestawu pytań
        //Do zapytań asynchronicznych
        public async Task<IActionResult> GetAreas()
        {
            try
            {
                //API zwraca pustą listę jeżeli jest brak elementów
                var areas = await _httpClient.GetAllItems<AreaViewModel>();
                return Ok(areas);
            }
            catch(HttpRequestException e)
            {
                return BadRequest(e.Message);
            }
        }

        public async Task<IActionResult> IndexArea()
        {
            var areas = new List<AreaViewModel>();
            try
            {
                areas = await _httpClient.GetAllItems<AreaViewModel>();
                return View(areas);
            }
            catch(HttpRequestException e)
            {
                TempData["errorAlert"] = $"Nie udało się pobrać obszarów. {e.Message}";
                return View(areas);
            }
        }

        public async Task<IActionResult> EditArea(byte id)
        {
            try
            {
                if (id == default(byte))
                    throw new DataValidationException(
                        "Nie znaleziono obszaru o podanym identyfikatorze");

                var area = await _httpClient.GetItemById<AreaViewModel>(id);

                return View(area);
            }
            catch(Exception e)
            {
                TempData["errorAlert"] = e.Message;
                return RedirectToAction(nameof(IndexArea));
            }
        }

        [HttpPost]
        public async Task<IActionResult> EditArea(AreaViewModel areaVM)
        {
            if (!ModelState.IsValid)
                return View(areaVM);

            try
            {
                await _httpClient.UpdateItem(areaVM);

                TempData["successAlert"] = "Poprawnie zaktualizowano obszar";
                return RedirectToAction(nameof(IndexArea));
            }
            catch (Exception e)
            {
                TempData["errorAlert"] = "Nieudana próba edycji obszaru";
                return View(areaVM);
            }
        }
        #endregion

        #region Skala trudności
        //Do zapytań asynchronicznych
        public async Task<IActionResult> GetDifficulties()
        {
            try
            {
                var difficulties = await _httpClient.GetAllItems<DifficultyViewModel>();
                return Ok(difficulties);
            }
            catch(HttpRequestException e)
            {
                return BadRequest(e.Message);
            }
        }

        public async Task<IActionResult> IndexDifficulty()
        {
            var difficulties = new List<DifficultyViewModel>();
            try
            {
                difficulties = await _httpClient.GetAllItems<DifficultyViewModel>();
                return View(difficulties);
            }
            catch(HttpRequestException e)
            {
                TempData["errorAlert"] = $"Nie udało się pobrać skal trudności. {e.Message}";
                return View(difficulties);
            }
        }

        public async Task<IActionResult> EditDifficulty(byte id)
        {
            try
            {
                var difficulty = new DifficultyViewModel();
                if (id == default(byte))
                    throw new DataNotFoundException(
                        "Nie znaleziono skali trudności o podanym identyfikatorze");

                difficulty = await _httpClient.GetItemById<DifficultyViewModel>(id);

                return View(difficulty);
            }
            catch(Exception e)
            {
                TempData["errorAlert"] = "Nieudana próba edycji skali trudności";
                return RedirectToAction(nameof(IndexDifficulty));
            }
        }

        [HttpPost]
        public async Task<IActionResult> EditDifficulty(DifficultyViewModel difficultyVM)
        {
            if (!ModelState.IsValid)
                return View(difficultyVM);

            try
            {
                await _httpClient.UpdateItem(difficultyVM);

                TempData["successAlert"] = "Poprawnie zaktualizowano skalę trudności";
                return RedirectToAction(nameof(IndexDifficulty));
            }
            catch (Exception e)
            {
                TempData["errorAlert"] = "Nieudana próba edycji skali trudności";
                return View(difficultyVM);
            }
        }
        #endregion
    }
}

PlacowkaOswiatowaQuiz/Views/Dictionary/EditArea.cshtml
@model AreaViewModel

<form asp-action="EditArea" method="post">
    <fieldset>
        <legend class="w-auto">Edycja obszaru zestawu pytań</legend>
        <input type="hidden" asp-for="@Model.Id" />
        <div class="mb-3">
            <label asp-for="@Model.Name" class="form-label"></label>
            <input type="text" asp-for="@Model.Name" class="form-control">
            <span asp-validation-for="@Model.Name" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="@Model.ExtendedName" class="form-label"></label>
            <input type="text" asp-for="@Model.ExtendedName" class="form-control">
            <span asp-validation-for="@Model.ExtendedName" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="@Model.Description" class="form-label"></label>
            <input type="text" asp-for="@Model.Description" class="form-control">
            <span asp-validation-for="@Model.Description" class="text-danger"></span>
        </div>
        <div class="container row">
            <button type="submit" class="btn btn-primary">Zapisz</button>
        </div>
    </fieldset>
</form>

PlacowkaOswiatowaQuiz/Views/Dictionary/EditDifficulty.cshtml
@model DifficultyViewModel

<form asp-action="EditDifficulty" method="post">
    <fieldset>
        <legend>Edycja skali trudności</legend>
        <input type="hidden" asp-for="@Model.Id" />
        <div class="mb-3">
            <label asp-for="@Model.Name" class="form-label"></label>
            <input type="text" asp-for="@Model.Name" class="form-control">
            <span asp-validation-for="@Model.Name" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="@Model.Description" class="form-label"></label>
            <input type="text" asp-for="@Model.Description" class="form-control">
            <span asp-validation-for="@Model.Description" class="text-danger"></span>
        </div>
        <div class="container row">
            <button type="submit" class="btn btn-primary">Zapisz</button>
        </div>
    </fieldset>
</form>

PlacowkaOswiatowaQuiz/Views/Dictionary/IndexArea.cshtml
@model IEnumerable<AreaViewModel>
@{ViewData["Title"] = "Obszary zestawów pytań";}

<div class="panel-heading">
    <div class="row">
        <div class="col-md-7">
            <h5><b>Lista obszarów zestawów pytań</b></h5>
        </div>
    </div>
</div>
<div id="divAlertArea">
    <partial name="~/Views/UIComponents/_bootstrapAlert.cshtml" />
</div>

<div class="panel-body scroll panel-height">
    <table class="table">
        <thead>
            <tr>
                <th>@Html.DisplayNameFor(model => model.Id)</th>
                <th>@Html.DisplayNameFor(model => model.Name)</th>
                <th>@Html.DisplayNameFor(model => model.Description)</th>
                <th></th>
                @*<th></th>*@
            </tr>
        </thead>

        <tbody>

            @foreach (var area in Model)
            {
                <tr>
                    <td>@Html.DisplayFor(item => area.Id)</td>
                    <td>@Html.DisplayFor(item => area.Name)</td>
                    <td>@Html.DisplayFor(item => area.Description)</td>
                    <td>
                        <div>
                            <a class="btn btn-sm btn-info" asp-controller="Dictionary" asp-action="EditArea" asp-route-id="@area.Id">
                                Edytuj
                            </a>
                            @*<a class="btn btn-sm btn-danger" asp-controller="Dictionary" asp-action="DeleteArea" asp-route-id="@area.Id">
                                    Usuń
                                </a>*@
                        </div>
                    </td>
                </tr>

            }

        </tbody>
    </table>
</div>

PlacowkaOswiatowaQuiz/Views/Dictionary/IndexDifficulty.cshtml
@model IEnumerable<DifficultyViewModel>
@{ViewData["Title"] = "Skale trudności";}

<div class="panel-heading">
    <div class="row">
        <div class="col-md-7">
            <h5><b>Lista skal trudności</b></h5>
        </div>
    </div>
</div>
<div id="divAlertArea">
    <partial name="~/Views/UIComponents/_bootstrapAlert.cshtml" />
</div>

<div class="panel-body scroll panel-height">
    <table class="table">
        <thead>
            <tr>
                <th>@Html.DisplayNameFor(model => model.Id)</th>
                <th>@Html.DisplayNameFor(model => model.Name)</th>
                <th>@Html.DisplayNameFor(model => model.Description)</th>
                <th></th>
                @*<th></th>*@
            </tr>
        </thead>

        <tbody>

            @foreach (var diff in Model)
            {
                <tr>
                    <td>@Html.DisplayFor(item => diff.Id)</td>
                    <td>@Html.DisplayFor(item => diff.Name)</td>
                    <td>@Html.DisplayFor(item => diff.Description)</td>
                    <td>
                        <div>
                            <a class="btn btn-sm btn-info" asp-controller="Dictionary" asp-action="EditDifficulty"
                               asp-route-id="@diff.Id">
                                Edytuj
                            </a>
                            @*<a class="btn btn-sm btn-danger" asp-controller="Dictionary" asp-action="DeleteDifficulty" asp-route-id="@diff.Id">
                                    Usuń
                                </a>*@
                        </div>
                    </td>
                </tr>

            }

        </tbody>
    </table>
</div>